---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonar
  labels:
    app: sonar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonar
  template:
    metadata:
      labels:
        app: sonar
    spec:
      containers:
      - name: sonar
        image: sonarqube:7.1
        ports:
        - containerPort: 9000
        - containerPort: 9092
---
apiVersion: v1
kind: Service
metadata:
  name: sonar
spec:
  selector:
    app: sonar
  ports:
  - protocol: TCP
    port: 9000
    targetPort: 9000
    nodePort: 30090
  type: NodePort
